<script type="text/javascript">
  var p = [
  "03.jpg",
  "04.jpg",
  "05.jpg",
  "06.jpg",
  "07.jpg",
  "08.jpg",
  "09.jpg",
  "IMG_0565_Panorama2.jpg",
  "IMG_7794.jpg",
  "IMG_7802.jpg",
  "IMG_7806.jpg",
  "IMG_7878.jpg",
  "IMG_7882.jpg",
  "IMG_7895.jpg",
  "IMG_7903.jpg",
  "IMG_7915.jpg"
  ]

  if(!window.photos) window.photos = [];
  window.photos.push({path : '/catalogue/hill-park-290/', photos: p});
</script>