<script type="text/javascript">
  var p = [
  "IMG_3343.JPG",
  "IMG_3338.JPG",
  "IMG_3340.JPG",
  "IMG_3341.JPG",
  "IMG_3337.JPG",
  "IMG_3339.JPG",
  "IMG_3059.JPG",
  "IMG_3072.JPG",
  "IMG_3075.JPG",
  "IMG_3076.JPG",
  "IMG_3065.JPG",
  "IMG_3073.JPG",
  "IMG_3068.JPG",
  "IMG_3070.JPG",
  "IMG_3074.JPG",
  "IMG_3064.JPG",
  "IMG_3071.JPG"
  ]

  if(!window.photos) window.photos = [];
  window.photos.push({path : '/catalogue/hill-park-221/', photos: p});
</script>