<%
Dim b
b = "?b=12"
%>

<link rel="shortcut icon" href="/favicon.ico" />
<link rel="shortcut icon" href="http://hillpark.ru/favicon.ico" type="image/x-icon" />
<link rel="icon" href="http://hillpark.ru/favicon.ico" type="image/x-icon" />

<meta name="description" content="Строительство загородных фахверковых домов под ключ компанией Hill Park. Цены на проектирование и постройку загородных коттеджей с зеленой кровлей по шведской технологии. Быстровозводимые комплекты фахверковых и каркасных домов, дома из клееного бруса.">
<meta name="keywords" content="строительство загородных домов, коттедж, комплекты фахверковых домов, комплекты каркасных домов, клееный брус, фахверк, шведская технология, быстровозводимые дома, быстрое строительство, под ключ, проектирование, цена, недорого, зеленая кровля, парк на крыше, экологичность, экодом">
<meta name="author" content="Hill Park">

<meta http-equiv="Content-Type" content="text/html; charset=utf-8" />

<link type="text/css" href="/inc/packages/jquery.bxslider/jquery.bxslider.css" rel="stylesheet" />
<link type="text/css" href="/inc/packages/jquery.photobox/photobox/photobox.css" rel="stylesheet" />

<link type="text/css" href="/inc/fonts.css<%=b%>" rel="stylesheet" />
<link type="text/css" href="/inc/kaptenen.css<%=b%>" rel="stylesheet" />
  
<script type="text/javascript" language="javascript" src="/inc/packages/jquery/jquery-1.9.1.min.js"></script>
<script type="text/javascript" language="javascript" src="/inc/packages/jquery/jquery.easing.min.1.3.js"></script>
<script type="text/javascript" language="javascript" src="/inc/packages/jquery.bxslider/jquery.bxslider.min.js"></script>
<script type="text/javascript" language="javascript" src="/inc/packages/jquery.photobox/photobox/jquery.photobox.min.js"></script>

<script type="text/javascript" language="javascript" src="/inc/kaptenen.js<%=b%>"></script>