<div class="site-banner">
	<div class="site-logo">
		<a href="/">
		<img src="/i/logo-top.png" /></a>
	</div>
</div>
<!--Menu-->
<div class="page-menu-background"><div class="page-menu">
	<a href="/">главная</a>
  <a href="/project/">о проекте</a>
  <a href="/catalogue/">каталог домов</a>
  <a href="/village/">о поселке</a>
  <a href="/location/">расположение</a>
  <!--<a href="/custom/">дома на заказ</a>-->
  <a href="/photo/">фото</a>
</div></div>