<script type="text/javascript">
  var p = [
  "img_4236.jpg",
  "img_4237.jpg",
  "img_4238.jpg",
  "img_4239.jpg",
  "img_4240.jpg",
  "img_4241.jpg",
  "img_4421.jpg",
  "img_8237.jpg",
  "img_8238.jpg",
  "img_8242.jpg",
  "img_8244.jpg",
  "img_8235.jpg",
  "img_8239.jpg",
  "img_8240.jpg",
  "img_8245.jpg",
  "img_8247.jpg",
  "img_7743.jpg",
  "img_8233.jpg",
  "img_8241.jpg",
  "img_8243.jpg",
  "img_8248.jpg"
  ]

  if(!window.photos) window.photos = [];
  window.photos.push({path : '/catalogue/hill-park-361/', photos: p});
</script>