<script type="text/javascript">
  var p = [
  "img_4885.jpg",
  "img_4936.jpg",
  "img_7190.jpg",
  "img_7376.jpg",
  "img_7378.jpg",
  "img_7379.jpg",
  "img_7460.jpg",
  "img_7461.jpg",
  "img_7462.jpg",
  "img_8857.jpg",
  "img_9364.jpg",
  "img_0764.jpg",
  "img_1631.jpg",
  "img_1754.jpg",
  "img_2204.jpg",
  "img_5558.jpg",
  "img_5559.jpg",
  ]

  if(!window.photos) window.photos = [];
  window.photos.push({path : '/catalogue/hill-park-222/', photos: p});
</script>