<script type="text/javascript">
  var p = [
  "img_2476.jpg",
  "img_2776.jpg",
  "img_2777.jpg",
  "img_2778.jpg",
  "img_2780.jpg",
  "img_2786.jpg",
  "img_2787.jpg",
  "img_2788.jpg",
  "img_2789.jpg",
  "img_2832.jpg",
  "09.jpg",
  "10.jpg",
  "11.jpg",
  "img_0463_panorama1.jpg",
  "img_8062.jpg",
  "img_8073.jpg",
  "img_8075.jpg",
  "img_8079.jpg",
  "img_8082.jpg",
  "img_7598.jpg",
  "img_7599.jpg",
  "img_7600.jpg",
  "img_7601.jpg",
  "img_7602.jpg",
  "img_7603.jpg",
  "img_7604.jpg",
  "img_7605.jpg",
  "img_7606.jpg",
  "img_7607.jpg",
  "img_7608.jpg",
  "img_7609.jpg",
  "img_7610.jpg",
  ]

  if(!window.photos) window.photos = [];
  window.photos.push({path : '/catalogue/hill-park-447/', photos: p});
</script>