<script type="text/javascript">
  var p = [
  "03.jpg",
  "04.jpg",
  "05.jpg",
  "06.jpg",
  "08.jpg",
  "09.jpg",
  "10.jpg",
  "11.jpg",
  "164_IMG_0115_Panorama1.jpg",
  "164_IMG_9334_Panorama1.jpg",
  "IMG_0463_Panorama1.jpg",
  "IMG_7717.jpg",
  "IMG_7723.jpg",
  "IMG_7756.jpg",
  "IMG_8055_HDR.jpg",
  "IMG_8062.jpg",
  "IMG_8070.jpg",
  "IMG_8071.jpg",
  "IMG_8073.jpg",
  "IMG_8075.jpg",
  "IMG_8079.jpg",
  "IMG_8082.jpg",
  "IMG_8083.jpg"
  ]

  if(!window.photos) window.photos = [];
  window.photos.push({path : '/catalogue/hill-park-447/', photos: p});
</script>