<script type="text/javascript">
  var p = [
  "IMG_2476.jpg",
  "IMG_2776.jpg",
  "IMG_2777.jpg",
  "IMG_2778.jpg",
  "IMG_2780.jpg",
  "IMG_2786.jpg",
  "IMG_2787.jpg",
  "IMG_2788.jpg",
  "IMG_2789.jpg",
  "IMG_2832.jpg",
  "09.jpg",
  "10.jpg",
  "11.jpg",
  "IMG_0463_Panorama1.jpg",
  "IMG_8062.jpg",
  "IMG_8073.jpg",
  "IMG_8075.jpg",
  "IMG_8079.jpg",
  "IMG_8082.jpg"
  ]

  if(!window.photos) window.photos = [];
  window.photos.push({path : '/catalogue/hill-park-447/', photos: p});
</script>