<script type="text/javascript">
  var p = [
  "img_3825.jpg",
  "img_3826.jpg",
  "img_3827.jpg",
  "img_3828.jpg",
  "img_3829.jpg",
  "img_4422.jpg",
  "img_7926.jpg",
  "img_7927.jpg",
  "img_7928.jpg",
  "img_7929.jpg",
  "img_7930.jpg",
  "img_7931.jpg",
  "img_7932.jpg",
  "img_7933.jpg",
  "img_7934.jpg",
  "img_7935.jpg",
  "img_7936.jpg",
  "img_7937.jpg"
  ]

  if(!window.photos) window.photos = [];
  window.photos.push({path : '/catalogue/hill-park-126/', photos: p});
</script>