<script type="text/javascript">
  var p = [
  "IMG_5011.JPG",
  "IMG_5012.JPG",
  "IMG_5013.JPG",
  "IMG_5014.JPG",
  "IMG_5015.JPG",
  "IMG_5021.JPG",
  "IMG_5024.JPG",
  "IMG_5030.JPG",
  "IMG_5022.JPG",
  "IMG_5304.JPG",
  "IMG_5305.JPG",
  "IMG_5018.JPG",
  "IMG_5028.JPG",
  "IMG_5027.JPG",
  "IMG_5029.JPG",
  "IMG_5017.JPG",
  "IMG_5026.JPG",
  "IMG_5020.JPG",
  "IMG_5016.JPG",
  "IMG_5023.JPG",
  "IMG_5025.JPG",
  "IMG_5300.JPG",
  "IMG_5301.JPG",
  "IMG_5303.JPG",
  "IMG_5308.JPG",
  "IMG_5302.JPG",
  "IMG_5307.JPG"  
  ]

  if(!window.photos) window.photos = [];
  window.photos.push({path : '/catalogue/hill-park-126/', photos: p});
</script>